name: sountrends
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  spotify: ^0.12.0
  spotify_sdk: ^2.3.1
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_web_auth: ^0.5.0
  url_launcher: ^6.2.1
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.4
  webview_flutter: ^4.4.2
  shelf_web_socket: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/logo.png
    - assets/logo_text.png
    - assets/natael.jpeg
    - assets/alien_boy.jpg
    
  uses-material-design: true
